# Model hyperparams
# See https://smp.readthedocs.io/en/latest/models.html#unet
# for full options
encoder_name: "mobilenet_v2"
encoder_depth: 5
encoder_weights: "imagenet" # put null for random init
decoder_channels: [256, 128, 64, 32, 16]
decoder_attention_type: null # Can be null or "scse"
in_channels: 3
out_channels: 19
# Activation on the last layer of the model, can be "sigmoid", "softmax", etc
activation: null

# Dataset hyperparams


# Training hyperparams
epochs: 10
batch_size: 2
learning_rate: 3e-3
loss: "Jaccard" # Supports "Jaccard" and "Focal"
checkpoint_freq: 1 # How many epochs we should train for before checkpointing the model.
# If val_interval is a float, it is the proportion of training set between validation epochs.
# If it is an int, it denotes the number of batches in between validation epochs.
val_interval: 0.25
log_steps: 20 # How many gradient updates between each log point.
parallel_engine: ddp
cuda: True # Whether to use GPUs.
gpus: 1 # Number of GPUs to use.
num_workers: 8 # Number of subprocesses to use for data loading.
seed: 42 # Random seed.
run_name: ??? # Mandatory string argument that describes the run.

# Hydra config overrides:
hydra:
  run:
    dir: logs/${run_name}
  sweep:
    dir: logs/${run_name}
