#!/bin/bash
echo "Running postBuild from" $(pwd)

echo "Downloading data for binder:"
wget -q -O binder_data.zip "https://docs.google.com/uc?export=download&id=1duTBmOPkj1fUK1H9TtG1j3VsSRovO0JR"

echo "Unzipping data for demonstration into data directory" 
unzip -d data binder_data.zip

echo "Removing data zip-file"
rm binder_data.zip

echo "unset PROJ_LIB environment variable for rasterio > 1.2.0"
unset PROJ_LIB