# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Continuous integration loop

# Triggers the workflow on pull request
# events but only for the master branch
on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest # OS to run the tests on

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pytest
          if [ -f requirements/test-requirements.txt ]; then pip install -r requirements/test-requirements.txt; fi

      - name: Lint with pylint
        run: |
          # lint with the rules defined in pylintrc
          pylint --ignore-patterns=lint_test geograph

# For unit tests later
#    - name: Test with pytest
#      run: |
#        pytest
#   - name: Test with coverage
#     run: |
#       pip3 install coverage
#       make test
#     env:
#       VIRTUAL_ENV: TRUE
